name: Deploy Back-End

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Setup SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-add - <<< "$SSH_PRIVATE_KEY"
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Debug SSH key
      run: |
        ls -la ~/.ssh
        cat ~/.ssh/id_rsa

    - name: Push to Epitech repo
      run: |
        git remote add epitech git@github.com:EpitechPromo2027/B-DEV-500-NCE-5-1-area-steven.deffontaine.git
        git push epitech main --force